Overt Garnet Dog

Medium

# missing auth modifier, causing loss of user funds when lock at different ``urn``

### Summary

#### ``LockstakeEngine#lock`` and ``LockstakeEngine#lockNgt`` have no ``urnAuth(urn)`` modifier.

#### As a result, everyone can "lock" with someone's urn.

#### Unfortunately, once they "lock". They cannot claim they token, which is perform "free".

### Root Cause

look at these function [lock](https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/dba30d7a676c20dfed3bda8c52fd6702e2e85bb1/lockstake/src/LockstakeEngine.sol#L309-L320): 
```solidity
  function lock(address urn, uint256 wad, uint16 ref) external {
        mkr.transferFrom(msg.sender, address(this), wad);
        _lock(urn, wad, ref);
        emit Lock(urn, wad, ref);
    }

    function lockNgt(address urn, uint256 ngtWad, uint16 ref) external {
        ngt.transferFrom(msg.sender, address(this), ngtWad);
        mkrNgt.ngtToMkr(address(this), ngtWad);
        _lock(urn, ngtWad / mkrNgtRate, ref);
        emit LockNgt(urn, ngtWad, ref);
    }
```
#### So, everyone can perform "locking" with one's urn, since those functions do not use the ``urnAuth(urn)`` modifier.
#### The ``urnAuth(urn)`` modifier is for check that caller of ``urn`` owner or allowed to used ``urn``.

#### Unfortunately, once they are "locked in", they cannot claim their token. Because the "free" function has ``urnAuth(urn)``. #### As a result, their token will belong to someone's `urn` that they used.

```solidity
    function free(address urn, address to, uint256 wad) external urnAuth(urn) returns (uint256 freed) {

    function freeNgt(address urn, address to, uint256 ngtWad) external urnAuth(urn) returns (uint256 ngtFreed) {

```


### Internal pre-conditions

_No response_

### External pre-conditions

_No response_

### Attack Path

_No response_

### Impact

#### As a result, users who ``lock`` with someone's ``urn``, their tokens will belong to that person.

### PoC

- paste this code to file ``LockstakeEngine.t.sol``
- run with ``forge test --match-test test_lock_in_wrong_urn``
```solidity
function test_lock_in_wrong_urn() public {
        address andi = makeAddr("andi");
        vm.prank(andi); 
        address urnAndi = engine.open(0);

        address jhon = makeAddr("jhon");
        vm.startPrank(jhon);
        deal(address(mkr), jhon, 100_000 * 10**18);
        mkr.approve(address(engine), 100_000 * 10**18);
        engine.lock(urnAndi, 100_000 * 10**18, 5);

        vm.expectRevert("LockstakeEngine/urn-not-authorized");
        engine.free(urnAndi, jhon, 100_000 * 10**18);
        
    }
```

### Mitigation

```solidity
+     function lock(address urn, uint256 wad, uint16 ref) external urnAuth(urn) {
+     function lockNgt(address urn, uint256 ngtWad, uint16 ref) external urnAuth(urn) {
```